### ISSUE TITLE
transaction support ?

### ISSUE THREAD

**Issue by amiracam** [cmichon/jruby-mapdb#3]
is every put committed to db file ? or does that happen upon close ?

any support for rolling back a series of map puts ?

thanks

**Comment by cmichon** [comment]
Hi,

Transactions are turned off by default, so every change is written by
default.

To enable transactions the library needs code change. I can look at it only
after new year. If it's and if you're familiar enough with my code and
MapDB, you can go ahead and make a git pull request.

**Comment by amiracam** [comment]
Just started becoming familiar :)

**Comment by amiracam** [comment]
Closed because of the library now supports transactions :)
