### ISSUE TITLE
more doc elaboration

### ISSUE THREAD

**Issue by amiracam** [cmichon/jruby-mapdb#4]
this is just a comment, your docs don't mention how to retrieve a tree that was previously persisted to file i.e. across sessions i.e. which would be a typical usage scenario.

No doubt to effectively use this one should also become acquainted with MapDB itself.

thanks

**Comment by cmichon** [comment]
Actually you just need to re-use the exact same lines from initial MapDB creation. This will allow reading back across sessions.

Please note that the 'schema' (ie list of trees) is not retrieved by just opening the MapDB. On top of this, jruby-mapdb stores ruby serialized objects via marshal, so you cannot expect to open a MapDB created with other tools: it's not meant for this usage.
